services:
  airnur:
    build: .
    ports:
      - 9090:8080
    depends_on:
      - postgres
  postgres:
    image: postgres:16-alpine
    ports:
      - 6969:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=msreserva