#!/usr/bin/env sh
archivos_cambiados=$(git diff --name-only head)
echo $archivos_cambiados
for archivo in $archivos_cambiados; do
    echo "archivo"
    mvn spring-javaformat:apply -Dspring-javaformat.glob=$archivo
done

git add .