#!/usr/bin/env sh
echo "archivo"
archivos_cambiados=$(git diff --name-only)
for archivo in $archivos_cambiados; do
  echo "archivo"
    mvn spring-javaformat:apply -Dspring-javaformat.glob=$archivo
done